version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    command: 'sh /entrypoint.sh'
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - postgres
